default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: 3306
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV['DATABASE_PASS'] %>

development:
  <<: *default
  database: funds_keeper_api_development

test:
  <<: *default
  database: funds_keeper_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10
  database: <%= ENV.fetch('DATABASE_NAME', 'funds_keeper_api_production') %>
